### ISSUE TITLE
TOC setting bug

### ISSUE THREAD

**Issue by jnkn6** [hugo-sid/hugo-blog-awesome#120]
**Describe the bug**
Cannot turn off TOC for a blog post when global setting of TOC is on.

**Steps to reproduce**
1. set global TOC setting as true
```toml
[params]
  toc = true # set to false to disable table of contents 'globally'
```
2. Turn off TOC setting for some post.

```
+++
title = "About"
toc = false
+++
```

**Expected behavior**
Should overwrite global config
